package cn.springmvc.model.sys;

import java.util.Date;

public class LogExplain {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column log_explain.id
	 * @mbggenerated  Tue Dec 20 17:36:07 CST 2016
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column log_explain.admin_id
	 * @mbggenerated  Tue Dec 20 17:36:07 CST 2016
	 */
	private Integer adminId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column log_explain.admin_name
	 * @mbggenerated  Tue Dec 20 17:36:07 CST 2016
	 */
	private String adminName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column log_explain.explain_content
	 * @mbggenerated  Tue Dec 20 17:36:07 CST 2016
	 */
	private String explainContent;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column log_explain.create_time
	 * @mbggenerated  Tue Dec 20 17:36:07 CST 2016
	 */
	private Date createTime;


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column log_explain.id
	 * @return  the value of log_explain.id
	 * @mbggenerated  Tue Dec 20 17:36:07 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column log_explain.id
	 * @param id  the value for log_explain.id
	 * @mbggenerated  Tue Dec 20 17:36:07 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column log_explain.admin_id
	 * @return  the value of log_explain.admin_id
	 * @mbggenerated  Tue Dec 20 17:36:07 CST 2016
	 */
	public Integer getAdminId() {
		return adminId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column log_explain.admin_id
	 * @param adminId  the value for log_explain.admin_id
	 * @mbggenerated  Tue Dec 20 17:36:07 CST 2016
	 */
	public void setAdminId(Integer adminId) {
		this.adminId = adminId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column log_explain.admin_name
	 * @return  the value of log_explain.admin_name
	 * @mbggenerated  Tue Dec 20 17:36:07 CST 2016
	 */
	public String getAdminName() {
		return adminName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column log_explain.admin_name
	 * @param adminName  the value for log_explain.admin_name
	 * @mbggenerated  Tue Dec 20 17:36:07 CST 2016
	 */
	public void setAdminName(String adminName) {
		this.adminName = adminName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column log_explain.explain_content
	 * @return  the value of log_explain.explain_content
	 * @mbggenerated  Tue Dec 20 17:36:07 CST 2016
	 */
	public String getExplainContent() {
		return explainContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column log_explain.explain_content
	 * @param explainContent  the value for log_explain.explain_content
	 * @mbggenerated  Tue Dec 20 17:36:07 CST 2016
	 */
	public void setExplainContent(String explainContent) {
		this.explainContent = explainContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column log_explain.create_time
	 * @return  the value of log_explain.create_time
	 * @mbggenerated  Tue Dec 20 17:36:07 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column log_explain.create_time
	 * @param createTime  the value for log_explain.create_time
	 * @mbggenerated  Tue Dec 20 17:36:07 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	private Integer pageNo;

	private Integer pageSize;
    

    public Integer getPageNo() {
		return pageNo;
	}

	public void setPageNo(Integer pageNo) {
		this.pageNo = pageNo;
	}

	public Integer getPageSize() {
		return pageSize;
	}

	public void setPageSize(Integer pageSize) {
		this.pageSize = pageSize;
	}
}