package cn.springmvc.model.sys;

public class Resource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.id
     *
     * @mbggenerated Thu Nov 10 11:59:48 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.admin_id
     *
     * @mbggenerated Thu Nov 10 11:59:48 CST 2016
     */
    private Integer adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.privilege_id
     *
     * @mbggenerated Thu Nov 10 11:59:48 CST 2016
     */
    private Integer privilegeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.id
     *
     * @return the value of resource.id
     *
     * @mbggenerated Thu Nov 10 11:59:48 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.id
     *
     * @param id the value for resource.id
     *
     * @mbggenerated Thu Nov 10 11:59:48 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.admin_id
     *
     * @return the value of resource.admin_id
     *
     * @mbggenerated Thu Nov 10 11:59:48 CST 2016
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.admin_id
     *
     * @param adminId the value for resource.admin_id
     *
     * @mbggenerated Thu Nov 10 11:59:48 CST 2016
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.privilege_id
     *
     * @return the value of resource.privilege_id
     *
     * @mbggenerated Thu Nov 10 11:59:48 CST 2016
     */
    public Integer getPrivilegeId() {
        return privilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.privilege_id
     *
     * @param privilegeId the value for resource.privilege_id
     *
     * @mbggenerated Thu Nov 10 11:59:48 CST 2016
     */
    public void setPrivilegeId(Integer privilegeId) {
        this.privilegeId = privilegeId;
    }
}