package hjzl.db.domain;

import java.util.Date;

import org.java_websocket.client.WebSocketClient;

public class UserBean {

	WebSocketClient client;
	
	public WebSocketClient getClient() {
		return client;
	}

	public void setClient(WebSocketClient client) {
		this.client = client;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.user_id
	 * @mbggenerated  Wed Dec 21 14:36:52 CST 2016
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.last_login_server_id
	 * @mbggenerated  Wed Dec 21 14:36:52 CST 2016
	 */
	private Integer lastLoginServerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.create_time
	 * @mbggenerated  Wed Dec 21 14:36:52 CST 2016
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.last_login_time
	 * @mbggenerated  Wed Dec 21 14:36:52 CST 2016
	 */
	private Date lastLoginTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.state
	 * @mbggenerated  Wed Dec 21 14:36:52 CST 2016
	 */
	private Integer state;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.user_id
	 * @return  the value of user.user_id
	 * @mbggenerated  Wed Dec 21 14:36:52 CST 2016
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.user_id
	 * @param userId  the value for user.user_id
	 * @mbggenerated  Wed Dec 21 14:36:52 CST 2016
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.last_login_server_id
	 * @return  the value of user.last_login_server_id
	 * @mbggenerated  Wed Dec 21 14:36:52 CST 2016
	 */
	public Integer getLastLoginServerId() {
		return lastLoginServerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.last_login_server_id
	 * @param lastLoginServerId  the value for user.last_login_server_id
	 * @mbggenerated  Wed Dec 21 14:36:52 CST 2016
	 */
	public void setLastLoginServerId(Integer lastLoginServerId) {
		this.lastLoginServerId = lastLoginServerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.create_time
	 * @return  the value of user.create_time
	 * @mbggenerated  Wed Dec 21 14:36:52 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.create_time
	 * @param createTime  the value for user.create_time
	 * @mbggenerated  Wed Dec 21 14:36:52 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.last_login_time
	 * @return  the value of user.last_login_time
	 * @mbggenerated  Wed Dec 21 14:36:52 CST 2016
	 */
	public Date getLastLoginTime() {
		return lastLoginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.last_login_time
	 * @param lastLoginTime  the value for user.last_login_time
	 * @mbggenerated  Wed Dec 21 14:36:52 CST 2016
	 */
	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.state
	 * @return  the value of user.state
	 * @mbggenerated  Wed Dec 21 14:36:52 CST 2016
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.state
	 * @param state  the value for user.state
	 * @mbggenerated  Wed Dec 21 14:36:52 CST 2016
	 */
	public void setState(Integer state) {
		this.state = state;
	}
}