package hjzl.db.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import hjzl.db.domain.UserBean;
import hjzl.db.domain.UserBeanExample;

public interface UserBeanMapper {
	
	List<UserBean> listLimit(@Param("page")int page,@Param("pageSize")int pageSize);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Wed Dec 21 14:36:52 CST 2016
	 */
	int countByExample(UserBeanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Wed Dec 21 14:36:52 CST 2016
	 */
	int deleteByExample(UserBeanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Wed Dec 21 14:36:52 CST 2016
	 */
	int deleteByPrimaryKey(Long userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Wed Dec 21 14:36:52 CST 2016
	 */
	int insert(UserBean record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Wed Dec 21 14:36:52 CST 2016
	 */
	int insertSelective(UserBean record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Wed Dec 21 14:36:52 CST 2016
	 */
	List<UserBean> selectByExample(UserBeanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Wed Dec 21 14:36:52 CST 2016
	 */
	UserBean selectByPrimaryKey(Long userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Wed Dec 21 14:36:52 CST 2016
	 */
	int updateByExampleSelective(@Param("record") UserBean record, @Param("example") UserBeanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Wed Dec 21 14:36:52 CST 2016
	 */
	int updateByExample(@Param("record") UserBean record, @Param("example") UserBeanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Wed Dec 21 14:36:52 CST 2016
	 */
	int updateByPrimaryKeySelective(UserBean record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Wed Dec 21 14:36:52 CST 2016
	 */
	int updateByPrimaryKey(UserBean record);
}