package cn.springmvc.dao.userdao;

import cn.springmvc.model.usermodel.SecurityCode;
import cn.springmvc.model.usermodel.SecurityCodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SecurityCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_code
     *
     * @mbggenerated Thu Jan 05 16:40:17 CST 2017
     */
    int countByExample(SecurityCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_code
     *
     * @mbggenerated Thu Jan 05 16:40:17 CST 2017
     */
    int deleteByExample(SecurityCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_code
     *
     * @mbggenerated Thu Jan 05 16:40:17 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_code
     *
     * @mbggenerated Thu Jan 05 16:40:17 CST 2017
     */
    int insert(SecurityCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_code
     *
     * @mbggenerated Thu Jan 05 16:40:17 CST 2017
     */
    int insertSelective(SecurityCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_code
     *
     * @mbggenerated Thu Jan 05 16:40:17 CST 2017
     */
    List<SecurityCode> selectByExample(SecurityCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_code
     *
     * @mbggenerated Thu Jan 05 16:40:17 CST 2017
     */
    SecurityCode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_code
     *
     * @mbggenerated Thu Jan 05 16:40:17 CST 2017
     */
    int updateByExampleSelective(@Param("record") SecurityCode record, @Param("example") SecurityCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_code
     *
     * @mbggenerated Thu Jan 05 16:40:17 CST 2017
     */
    int updateByExample(@Param("record") SecurityCode record, @Param("example") SecurityCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_code
     *
     * @mbggenerated Thu Jan 05 16:40:17 CST 2017
     */
    int updateByPrimaryKeySelective(SecurityCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_code
     *
     * @mbggenerated Thu Jan 05 16:40:17 CST 2017
     */
    int updateByPrimaryKey(SecurityCode record);
}