package cn.springmvc.model.mall;

public class Mall {
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mall.id
	 * @mbggenerated  Thu May 10 19:21:03 CST 2018
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mall.company_id
	 * @mbggenerated  Thu May 10 19:21:03 CST 2018
	 */
	private Integer companyId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mall.mall_img
	 * @mbggenerated  Thu May 10 19:21:03 CST 2018
	 */
	private String mallImg;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mall.mall_introduce
	 * @mbggenerated  Thu May 10 19:21:03 CST 2018
	 */
	private String mallIntroduce;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mall.company_name
	 * @mbggenerated  Thu May 10 19:21:03 CST 2018
	 */
	private String companyName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mall.state
	 * @mbggenerated  Thu May 10 19:21:03 CST 2018
	 */
	private Integer state;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mall.id
	 * @return  the value of mall.id
	 * @mbggenerated  Thu May 10 19:21:03 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mall.id
	 * @param id  the value for mall.id
	 * @mbggenerated  Thu May 10 19:21:03 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mall.company_id
	 * @return  the value of mall.company_id
	 * @mbggenerated  Thu May 10 19:21:03 CST 2018
	 */
	public Integer getCompanyId() {
		return companyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mall.company_id
	 * @param companyId  the value for mall.company_id
	 * @mbggenerated  Thu May 10 19:21:03 CST 2018
	 */
	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mall.mall_img
	 * @return  the value of mall.mall_img
	 * @mbggenerated  Thu May 10 19:21:03 CST 2018
	 */
	public String getMallImg() {
		return mallImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mall.mall_img
	 * @param mallImg  the value for mall.mall_img
	 * @mbggenerated  Thu May 10 19:21:03 CST 2018
	 */
	public void setMallImg(String mallImg) {
		this.mallImg = mallImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mall.mall_introduce
	 * @return  the value of mall.mall_introduce
	 * @mbggenerated  Thu May 10 19:21:03 CST 2018
	 */
	public String getMallIntroduce() {
		return mallIntroduce;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mall.mall_introduce
	 * @param mallIntroduce  the value for mall.mall_introduce
	 * @mbggenerated  Thu May 10 19:21:03 CST 2018
	 */
	public void setMallIntroduce(String mallIntroduce) {
		this.mallIntroduce = mallIntroduce;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mall.company_name
	 * @return  the value of mall.company_name
	 * @mbggenerated  Thu May 10 19:21:03 CST 2018
	 */
	public String getCompanyName() {
		return companyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mall.company_name
	 * @param companyName  the value for mall.company_name
	 * @mbggenerated  Thu May 10 19:21:03 CST 2018
	 */
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mall.state
	 * @return  the value of mall.state
	 * @mbggenerated  Thu May 10 19:21:03 CST 2018
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mall.state
	 * @param state  the value for mall.state
	 * @mbggenerated  Thu May 10 19:21:03 CST 2018
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	private Integer pageNo;
	
	private Integer pageSize;
	
    public Integer getPageNo() {
		return pageNo;
	}

	public void setPageNo(Integer pageNo) {
		this.pageNo = pageNo;
	}

	public Integer getPageSize() {
		return pageSize;
	}

	public void setPageSize(Integer pageSize) {
		this.pageSize = pageSize;
	}
}