package com.rt.db.domain;

import java.util.Date;

public class RechagreOrder {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rechagre_order.order_id
	 * @mbggenerated  Tue Jul 24 15:16:40 CST 2018
	 */
	private String orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rechagre_order.user_name
	 * @mbggenerated  Tue Jul 24 15:16:40 CST 2018
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rechagre_order.product_name
	 * @mbggenerated  Tue Jul 24 15:16:40 CST 2018
	 */
	private String productName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rechagre_order.amount
	 * @mbggenerated  Tue Jul 24 15:16:40 CST 2018
	 */
	private Integer amount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rechagre_order.role_id
	 * @mbggenerated  Tue Jul 24 15:16:40 CST 2018
	 */
	private String roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rechagre_order.server_id
	 * @mbggenerated  Tue Jul 24 15:16:40 CST 2018
	 */
	private String serverId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rechagre_order.paytime
	 * @mbggenerated  Tue Jul 24 15:16:40 CST 2018
	 */
	private Long paytime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rechagre_order.state
	 * @mbggenerated  Tue Jul 24 15:16:40 CST 2018
	 */
	private Integer state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rechagre_order.create_time
	 * @mbggenerated  Tue Jul 24 15:16:40 CST 2018
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rechagre_order.order_id
	 * @return  the value of rechagre_order.order_id
	 * @mbggenerated  Tue Jul 24 15:16:40 CST 2018
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rechagre_order.order_id
	 * @param orderId  the value for rechagre_order.order_id
	 * @mbggenerated  Tue Jul 24 15:16:40 CST 2018
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rechagre_order.user_name
	 * @return  the value of rechagre_order.user_name
	 * @mbggenerated  Tue Jul 24 15:16:40 CST 2018
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rechagre_order.user_name
	 * @param userName  the value for rechagre_order.user_name
	 * @mbggenerated  Tue Jul 24 15:16:40 CST 2018
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rechagre_order.product_name
	 * @return  the value of rechagre_order.product_name
	 * @mbggenerated  Tue Jul 24 15:16:40 CST 2018
	 */
	public String getProductName() {
		return productName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rechagre_order.product_name
	 * @param productName  the value for rechagre_order.product_name
	 * @mbggenerated  Tue Jul 24 15:16:40 CST 2018
	 */
	public void setProductName(String productName) {
		this.productName = productName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rechagre_order.amount
	 * @return  the value of rechagre_order.amount
	 * @mbggenerated  Tue Jul 24 15:16:40 CST 2018
	 */
	public Integer getAmount() {
		return amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rechagre_order.amount
	 * @param amount  the value for rechagre_order.amount
	 * @mbggenerated  Tue Jul 24 15:16:40 CST 2018
	 */
	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rechagre_order.role_id
	 * @return  the value of rechagre_order.role_id
	 * @mbggenerated  Tue Jul 24 15:16:40 CST 2018
	 */
	public String getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rechagre_order.role_id
	 * @param roleId  the value for rechagre_order.role_id
	 * @mbggenerated  Tue Jul 24 15:16:40 CST 2018
	 */
	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rechagre_order.server_id
	 * @return  the value of rechagre_order.server_id
	 * @mbggenerated  Tue Jul 24 15:16:40 CST 2018
	 */
	public String getServerId() {
		return serverId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rechagre_order.server_id
	 * @param serverId  the value for rechagre_order.server_id
	 * @mbggenerated  Tue Jul 24 15:16:40 CST 2018
	 */
	public void setServerId(String serverId) {
		this.serverId = serverId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rechagre_order.paytime
	 * @return  the value of rechagre_order.paytime
	 * @mbggenerated  Tue Jul 24 15:16:40 CST 2018
	 */
	public Long getPaytime() {
		return paytime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rechagre_order.paytime
	 * @param paytime  the value for rechagre_order.paytime
	 * @mbggenerated  Tue Jul 24 15:16:40 CST 2018
	 */
	public void setPaytime(Long paytime) {
		this.paytime = paytime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rechagre_order.state
	 * @return  the value of rechagre_order.state
	 * @mbggenerated  Tue Jul 24 15:16:40 CST 2018
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rechagre_order.state
	 * @param state  the value for rechagre_order.state
	 * @mbggenerated  Tue Jul 24 15:16:40 CST 2018
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rechagre_order.create_time
	 * @return  the value of rechagre_order.create_time
	 * @mbggenerated  Tue Jul 24 15:16:40 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rechagre_order.create_time
	 * @param createTime  the value for rechagre_order.create_time
	 * @mbggenerated  Tue Jul 24 15:16:40 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}