package cn.springmvc.model.poster;

import java.util.Date;

public class WxpayFlowingWater {
	
	private Integer pageNo;
	
	private Integer pageSize;
	
    public Integer getPageNo() {
		return pageNo;
	}

	public void setPageNo(Integer pageNo) {
		this.pageNo = pageNo;
	}

	public Integer getPageSize() {
		return pageSize;
	}

	public void setPageSize(Integer pageSize) {
		this.pageSize = pageSize;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxpay_flowing_water.out_trade_no
     *
     * @mbggenerated Wed Jun 27 01:14:41 CST 2018
     */
    private String outTradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxpay_flowing_water.account
     *
     * @mbggenerated Wed Jun 27 01:14:41 CST 2018
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxpay_flowing_water.transaction_id
     *
     * @mbggenerated Wed Jun 27 01:14:41 CST 2018
     */
    private String transactionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxpay_flowing_water.trade_status
     *
     * @mbggenerated Wed Jun 27 01:14:41 CST 2018
     */
    private Integer tradeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxpay_flowing_water.vip_recharge_id
     *
     * @mbggenerated Wed Jun 27 01:14:41 CST 2018
     */
    private Integer vipRechargeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxpay_flowing_water.total_fee
     *
     * @mbggenerated Wed Jun 27 01:14:41 CST 2018
     */
    private Integer totalFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxpay_flowing_water.trading_time
     *
     * @mbggenerated Wed Jun 27 01:14:41 CST 2018
     */
    private Date tradingTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxpay_flowing_water.trading_success_time
     *
     * @mbggenerated Wed Jun 27 01:14:41 CST 2018
     */
    private Date tradingSuccessTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxpay_flowing_water.out_trade_no
     *
     * @return the value of wxpay_flowing_water.out_trade_no
     *
     * @mbggenerated Wed Jun 27 01:14:41 CST 2018
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxpay_flowing_water.out_trade_no
     *
     * @param outTradeNo the value for wxpay_flowing_water.out_trade_no
     *
     * @mbggenerated Wed Jun 27 01:14:41 CST 2018
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxpay_flowing_water.account
     *
     * @return the value of wxpay_flowing_water.account
     *
     * @mbggenerated Wed Jun 27 01:14:41 CST 2018
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxpay_flowing_water.account
     *
     * @param account the value for wxpay_flowing_water.account
     *
     * @mbggenerated Wed Jun 27 01:14:41 CST 2018
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxpay_flowing_water.transaction_id
     *
     * @return the value of wxpay_flowing_water.transaction_id
     *
     * @mbggenerated Wed Jun 27 01:14:41 CST 2018
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxpay_flowing_water.transaction_id
     *
     * @param transactionId the value for wxpay_flowing_water.transaction_id
     *
     * @mbggenerated Wed Jun 27 01:14:41 CST 2018
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxpay_flowing_water.trade_status
     *
     * @return the value of wxpay_flowing_water.trade_status
     *
     * @mbggenerated Wed Jun 27 01:14:41 CST 2018
     */
    public Integer getTradeStatus() {
        return tradeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxpay_flowing_water.trade_status
     *
     * @param tradeStatus the value for wxpay_flowing_water.trade_status
     *
     * @mbggenerated Wed Jun 27 01:14:41 CST 2018
     */
    public void setTradeStatus(Integer tradeStatus) {
        this.tradeStatus = tradeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxpay_flowing_water.vip_recharge_id
     *
     * @return the value of wxpay_flowing_water.vip_recharge_id
     *
     * @mbggenerated Wed Jun 27 01:14:41 CST 2018
     */
    public Integer getVipRechargeId() {
        return vipRechargeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxpay_flowing_water.vip_recharge_id
     *
     * @param vipRechargeId the value for wxpay_flowing_water.vip_recharge_id
     *
     * @mbggenerated Wed Jun 27 01:14:41 CST 2018
     */
    public void setVipRechargeId(Integer vipRechargeId) {
        this.vipRechargeId = vipRechargeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxpay_flowing_water.total_fee
     *
     * @return the value of wxpay_flowing_water.total_fee
     *
     * @mbggenerated Wed Jun 27 01:14:41 CST 2018
     */
    public Integer getTotalFee() {
        return totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxpay_flowing_water.total_fee
     *
     * @param totalFee the value for wxpay_flowing_water.total_fee
     *
     * @mbggenerated Wed Jun 27 01:14:41 CST 2018
     */
    public void setTotalFee(Integer totalFee) {
        this.totalFee = totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxpay_flowing_water.trading_time
     *
     * @return the value of wxpay_flowing_water.trading_time
     *
     * @mbggenerated Wed Jun 27 01:14:41 CST 2018
     */
    public Date getTradingTime() {
        return tradingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxpay_flowing_water.trading_time
     *
     * @param tradingTime the value for wxpay_flowing_water.trading_time
     *
     * @mbggenerated Wed Jun 27 01:14:41 CST 2018
     */
    public void setTradingTime(Date tradingTime) {
        this.tradingTime = tradingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxpay_flowing_water.trading_success_time
     *
     * @return the value of wxpay_flowing_water.trading_success_time
     *
     * @mbggenerated Wed Jun 27 01:14:41 CST 2018
     */
    public Date getTradingSuccessTime() {
        return tradingSuccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxpay_flowing_water.trading_success_time
     *
     * @param tradingSuccessTime the value for wxpay_flowing_water.trading_success_time
     *
     * @mbggenerated Wed Jun 27 01:14:41 CST 2018
     */
    public void setTradingSuccessTime(Date tradingSuccessTime) {
        this.tradingSuccessTime = tradingSuccessTime;
    }
}