package cn.springmvc.dao.game;

import cn.springmvc.model.game.GameCodeKey;
import cn.springmvc.model.game.GameCodeKeyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GameCodeKeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_code_key
     *
     * @mbggenerated Tue Jul 24 18:44:36 CST 2018
     */
    int countByExample(GameCodeKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_code_key
     *
     * @mbggenerated Tue Jul 24 18:44:36 CST 2018
     */
    int deleteByExample(GameCodeKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_code_key
     *
     * @mbggenerated Tue Jul 24 18:44:36 CST 2018
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_code_key
     *
     * @mbggenerated Tue Jul 24 18:44:36 CST 2018
     */
    int insert(GameCodeKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_code_key
     *
     * @mbggenerated Tue Jul 24 18:44:36 CST 2018
     */
    int insertSelective(GameCodeKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_code_key
     *
     * @mbggenerated Tue Jul 24 18:44:36 CST 2018
     */
    List<GameCodeKey> selectByExample(GameCodeKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_code_key
     *
     * @mbggenerated Tue Jul 24 18:44:36 CST 2018
     */
    GameCodeKey selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_code_key
     *
     * @mbggenerated Tue Jul 24 18:44:36 CST 2018
     */
    int updateByExampleSelective(@Param("record") GameCodeKey record, @Param("example") GameCodeKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_code_key
     *
     * @mbggenerated Tue Jul 24 18:44:36 CST 2018
     */
    int updateByExample(@Param("record") GameCodeKey record, @Param("example") GameCodeKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_code_key
     *
     * @mbggenerated Tue Jul 24 18:44:36 CST 2018
     */
    int updateByPrimaryKeySelective(GameCodeKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_code_key
     *
     * @mbggenerated Tue Jul 24 18:44:36 CST 2018
     */
    int updateByPrimaryKey(GameCodeKey record);
}