package cn.springmvc.dao.game;

import cn.springmvc.model.game.GiftCode;
import cn.springmvc.model.game.GiftCodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GiftCodeMapper {
	
	Integer maxId();
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_code
     *
     * @mbggenerated Tue Jul 24 18:11:40 CST 2018
     */
    int countByExample(GiftCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_code
     *
     * @mbggenerated Tue Jul 24 18:11:40 CST 2018
     */
    int deleteByExample(GiftCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_code
     *
     * @mbggenerated Tue Jul 24 18:11:40 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_code
     *
     * @mbggenerated Tue Jul 24 18:11:40 CST 2018
     */
    int insert(GiftCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_code
     *
     * @mbggenerated Tue Jul 24 18:11:40 CST 2018
     */
    int insertSelective(GiftCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_code
     *
     * @mbggenerated Tue Jul 24 18:11:40 CST 2018
     */
    List<GiftCode> selectByExample(GiftCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_code
     *
     * @mbggenerated Tue Jul 24 18:11:40 CST 2018
     */
    GiftCode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_code
     *
     * @mbggenerated Tue Jul 24 18:11:40 CST 2018
     */
    int updateByExampleSelective(@Param("record") GiftCode record, @Param("example") GiftCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_code
     *
     * @mbggenerated Tue Jul 24 18:11:40 CST 2018
     */
    int updateByExample(@Param("record") GiftCode record, @Param("example") GiftCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_code
     *
     * @mbggenerated Tue Jul 24 18:11:40 CST 2018
     */
    int updateByPrimaryKeySelective(GiftCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift_code
     *
     * @mbggenerated Tue Jul 24 18:11:40 CST 2018
     */
    int updateByPrimaryKey(GiftCode record);
}