package cn.springmvc.model.game;

import java.util.Date;

public class GameEmail {
	
	private String[] serverArray;

	private String starTime_1;
	
	private String endTime_1;

    private Integer pageNo;
	
	private Integer pageSize;

	public String[] getServerArray() {
		return serverArray;
	}

	public void setServerArray(String[] serverArray) {
		this.serverArray = serverArray;
	}

	public String getStarTime_1() {
		return starTime_1;
	}

	public void setStarTime_1(String starTime_1) {
		this.starTime_1 = starTime_1;
	}

	public String getEndTime_1() {
		return endTime_1;
	}

	public void setEndTime_1(String endTime_1) {
		this.endTime_1 = endTime_1;
	}

	public Integer getPageNo() {
		return pageNo;
	}

	public void setPageNo(Integer pageNo) {
		this.pageNo = pageNo;
	}

	public Integer getPageSize() {
		return pageSize;
	}

	public void setPageSize(Integer pageSize) {
		this.pageSize = pageSize;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column game_email.email_id
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	private Integer emailId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column game_email.target_server
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	private String targetServer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column game_email.email_title
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	private String emailTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column game_email.email_content
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	private String emailContent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column game_email.user_type
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	private Integer userType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column game_email.user_id_all
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	private String userIdAll;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column game_email.item_all
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	private String itemAll;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column game_email.star_time
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	private Date starTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column game_email.end_time
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	private Date endTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column game_email.create_admin_id
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	private Integer createAdminId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column game_email.create_admin_name
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	private String createAdminName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column game_email.create_time
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column game_email.email_id
	 * @return  the value of game_email.email_id
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	public Integer getEmailId() {
		return emailId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column game_email.email_id
	 * @param emailId  the value for game_email.email_id
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	public void setEmailId(Integer emailId) {
		this.emailId = emailId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column game_email.target_server
	 * @return  the value of game_email.target_server
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	public String getTargetServer() {
		return targetServer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column game_email.target_server
	 * @param targetServer  the value for game_email.target_server
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	public void setTargetServer(String targetServer) {
		this.targetServer = targetServer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column game_email.email_title
	 * @return  the value of game_email.email_title
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	public String getEmailTitle() {
		return emailTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column game_email.email_title
	 * @param emailTitle  the value for game_email.email_title
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	public void setEmailTitle(String emailTitle) {
		this.emailTitle = emailTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column game_email.email_content
	 * @return  the value of game_email.email_content
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	public String getEmailContent() {
		return emailContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column game_email.email_content
	 * @param emailContent  the value for game_email.email_content
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	public void setEmailContent(String emailContent) {
		this.emailContent = emailContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column game_email.user_type
	 * @return  the value of game_email.user_type
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	public Integer getUserType() {
		return userType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column game_email.user_type
	 * @param userType  the value for game_email.user_type
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	public void setUserType(Integer userType) {
		this.userType = userType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column game_email.user_id_all
	 * @return  the value of game_email.user_id_all
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	public String getUserIdAll() {
		return userIdAll;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column game_email.user_id_all
	 * @param userIdAll  the value for game_email.user_id_all
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	public void setUserIdAll(String userIdAll) {
		this.userIdAll = userIdAll;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column game_email.item_all
	 * @return  the value of game_email.item_all
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	public String getItemAll() {
		return itemAll;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column game_email.item_all
	 * @param itemAll  the value for game_email.item_all
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	public void setItemAll(String itemAll) {
		this.itemAll = itemAll;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column game_email.star_time
	 * @return  the value of game_email.star_time
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	public Date getStarTime() {
		return starTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column game_email.star_time
	 * @param starTime  the value for game_email.star_time
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	public void setStarTime(Date starTime) {
		this.starTime = starTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column game_email.end_time
	 * @return  the value of game_email.end_time
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column game_email.end_time
	 * @param endTime  the value for game_email.end_time
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column game_email.create_admin_id
	 * @return  the value of game_email.create_admin_id
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	public Integer getCreateAdminId() {
		return createAdminId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column game_email.create_admin_id
	 * @param createAdminId  the value for game_email.create_admin_id
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	public void setCreateAdminId(Integer createAdminId) {
		this.createAdminId = createAdminId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column game_email.create_admin_name
	 * @return  the value of game_email.create_admin_name
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	public String getCreateAdminName() {
		return createAdminName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column game_email.create_admin_name
	 * @param createAdminName  the value for game_email.create_admin_name
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	public void setCreateAdminName(String createAdminName) {
		this.createAdminName = createAdminName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column game_email.create_time
	 * @return  the value of game_email.create_time
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column game_email.create_time
	 * @param createTime  the value for game_email.create_time
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}