package cn.springmvc.model.game;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GameEmailExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table game_email
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table game_email
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table game_email
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table game_email
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	public GameEmailExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table game_email
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table game_email
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table game_email
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table game_email
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table game_email
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table game_email
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table game_email
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table game_email
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table game_email
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table game_email
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table game_email
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andEmailIdIsNull() {
			addCriterion("email_id is null");
			return (Criteria) this;
		}

		public Criteria andEmailIdIsNotNull() {
			addCriterion("email_id is not null");
			return (Criteria) this;
		}

		public Criteria andEmailIdEqualTo(Integer value) {
			addCriterion("email_id =", value, "emailId");
			return (Criteria) this;
		}

		public Criteria andEmailIdNotEqualTo(Integer value) {
			addCriterion("email_id <>", value, "emailId");
			return (Criteria) this;
		}

		public Criteria andEmailIdGreaterThan(Integer value) {
			addCriterion("email_id >", value, "emailId");
			return (Criteria) this;
		}

		public Criteria andEmailIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("email_id >=", value, "emailId");
			return (Criteria) this;
		}

		public Criteria andEmailIdLessThan(Integer value) {
			addCriterion("email_id <", value, "emailId");
			return (Criteria) this;
		}

		public Criteria andEmailIdLessThanOrEqualTo(Integer value) {
			addCriterion("email_id <=", value, "emailId");
			return (Criteria) this;
		}

		public Criteria andEmailIdIn(List<Integer> values) {
			addCriterion("email_id in", values, "emailId");
			return (Criteria) this;
		}

		public Criteria andEmailIdNotIn(List<Integer> values) {
			addCriterion("email_id not in", values, "emailId");
			return (Criteria) this;
		}

		public Criteria andEmailIdBetween(Integer value1, Integer value2) {
			addCriterion("email_id between", value1, value2, "emailId");
			return (Criteria) this;
		}

		public Criteria andEmailIdNotBetween(Integer value1, Integer value2) {
			addCriterion("email_id not between", value1, value2, "emailId");
			return (Criteria) this;
		}

		public Criteria andTargetServerIsNull() {
			addCriterion("target_server is null");
			return (Criteria) this;
		}

		public Criteria andTargetServerIsNotNull() {
			addCriterion("target_server is not null");
			return (Criteria) this;
		}

		public Criteria andTargetServerEqualTo(String value) {
			addCriterion("target_server =", value, "targetServer");
			return (Criteria) this;
		}

		public Criteria andTargetServerNotEqualTo(String value) {
			addCriterion("target_server <>", value, "targetServer");
			return (Criteria) this;
		}

		public Criteria andTargetServerGreaterThan(String value) {
			addCriterion("target_server >", value, "targetServer");
			return (Criteria) this;
		}

		public Criteria andTargetServerGreaterThanOrEqualTo(String value) {
			addCriterion("target_server >=", value, "targetServer");
			return (Criteria) this;
		}

		public Criteria andTargetServerLessThan(String value) {
			addCriterion("target_server <", value, "targetServer");
			return (Criteria) this;
		}

		public Criteria andTargetServerLessThanOrEqualTo(String value) {
			addCriterion("target_server <=", value, "targetServer");
			return (Criteria) this;
		}

		public Criteria andTargetServerLike(String value) {
			addCriterion("target_server like", value, "targetServer");
			return (Criteria) this;
		}

		public Criteria andTargetServerNotLike(String value) {
			addCriterion("target_server not like", value, "targetServer");
			return (Criteria) this;
		}

		public Criteria andTargetServerIn(List<String> values) {
			addCriterion("target_server in", values, "targetServer");
			return (Criteria) this;
		}

		public Criteria andTargetServerNotIn(List<String> values) {
			addCriterion("target_server not in", values, "targetServer");
			return (Criteria) this;
		}

		public Criteria andTargetServerBetween(String value1, String value2) {
			addCriterion("target_server between", value1, value2, "targetServer");
			return (Criteria) this;
		}

		public Criteria andTargetServerNotBetween(String value1, String value2) {
			addCriterion("target_server not between", value1, value2, "targetServer");
			return (Criteria) this;
		}

		public Criteria andEmailTitleIsNull() {
			addCriterion("email_title is null");
			return (Criteria) this;
		}

		public Criteria andEmailTitleIsNotNull() {
			addCriterion("email_title is not null");
			return (Criteria) this;
		}

		public Criteria andEmailTitleEqualTo(String value) {
			addCriterion("email_title =", value, "emailTitle");
			return (Criteria) this;
		}

		public Criteria andEmailTitleNotEqualTo(String value) {
			addCriterion("email_title <>", value, "emailTitle");
			return (Criteria) this;
		}

		public Criteria andEmailTitleGreaterThan(String value) {
			addCriterion("email_title >", value, "emailTitle");
			return (Criteria) this;
		}

		public Criteria andEmailTitleGreaterThanOrEqualTo(String value) {
			addCriterion("email_title >=", value, "emailTitle");
			return (Criteria) this;
		}

		public Criteria andEmailTitleLessThan(String value) {
			addCriterion("email_title <", value, "emailTitle");
			return (Criteria) this;
		}

		public Criteria andEmailTitleLessThanOrEqualTo(String value) {
			addCriterion("email_title <=", value, "emailTitle");
			return (Criteria) this;
		}

		public Criteria andEmailTitleLike(String value) {
			addCriterion("email_title like", value, "emailTitle");
			return (Criteria) this;
		}

		public Criteria andEmailTitleNotLike(String value) {
			addCriterion("email_title not like", value, "emailTitle");
			return (Criteria) this;
		}

		public Criteria andEmailTitleIn(List<String> values) {
			addCriterion("email_title in", values, "emailTitle");
			return (Criteria) this;
		}

		public Criteria andEmailTitleNotIn(List<String> values) {
			addCriterion("email_title not in", values, "emailTitle");
			return (Criteria) this;
		}

		public Criteria andEmailTitleBetween(String value1, String value2) {
			addCriterion("email_title between", value1, value2, "emailTitle");
			return (Criteria) this;
		}

		public Criteria andEmailTitleNotBetween(String value1, String value2) {
			addCriterion("email_title not between", value1, value2, "emailTitle");
			return (Criteria) this;
		}

		public Criteria andEmailContentIsNull() {
			addCriterion("email_content is null");
			return (Criteria) this;
		}

		public Criteria andEmailContentIsNotNull() {
			addCriterion("email_content is not null");
			return (Criteria) this;
		}

		public Criteria andEmailContentEqualTo(String value) {
			addCriterion("email_content =", value, "emailContent");
			return (Criteria) this;
		}

		public Criteria andEmailContentNotEqualTo(String value) {
			addCriterion("email_content <>", value, "emailContent");
			return (Criteria) this;
		}

		public Criteria andEmailContentGreaterThan(String value) {
			addCriterion("email_content >", value, "emailContent");
			return (Criteria) this;
		}

		public Criteria andEmailContentGreaterThanOrEqualTo(String value) {
			addCriterion("email_content >=", value, "emailContent");
			return (Criteria) this;
		}

		public Criteria andEmailContentLessThan(String value) {
			addCriterion("email_content <", value, "emailContent");
			return (Criteria) this;
		}

		public Criteria andEmailContentLessThanOrEqualTo(String value) {
			addCriterion("email_content <=", value, "emailContent");
			return (Criteria) this;
		}

		public Criteria andEmailContentLike(String value) {
			addCriterion("email_content like", value, "emailContent");
			return (Criteria) this;
		}

		public Criteria andEmailContentNotLike(String value) {
			addCriterion("email_content not like", value, "emailContent");
			return (Criteria) this;
		}

		public Criteria andEmailContentIn(List<String> values) {
			addCriterion("email_content in", values, "emailContent");
			return (Criteria) this;
		}

		public Criteria andEmailContentNotIn(List<String> values) {
			addCriterion("email_content not in", values, "emailContent");
			return (Criteria) this;
		}

		public Criteria andEmailContentBetween(String value1, String value2) {
			addCriterion("email_content between", value1, value2, "emailContent");
			return (Criteria) this;
		}

		public Criteria andEmailContentNotBetween(String value1, String value2) {
			addCriterion("email_content not between", value1, value2, "emailContent");
			return (Criteria) this;
		}

		public Criteria andUserTypeIsNull() {
			addCriterion("user_type is null");
			return (Criteria) this;
		}

		public Criteria andUserTypeIsNotNull() {
			addCriterion("user_type is not null");
			return (Criteria) this;
		}

		public Criteria andUserTypeEqualTo(Integer value) {
			addCriterion("user_type =", value, "userType");
			return (Criteria) this;
		}

		public Criteria andUserTypeNotEqualTo(Integer value) {
			addCriterion("user_type <>", value, "userType");
			return (Criteria) this;
		}

		public Criteria andUserTypeGreaterThan(Integer value) {
			addCriterion("user_type >", value, "userType");
			return (Criteria) this;
		}

		public Criteria andUserTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("user_type >=", value, "userType");
			return (Criteria) this;
		}

		public Criteria andUserTypeLessThan(Integer value) {
			addCriterion("user_type <", value, "userType");
			return (Criteria) this;
		}

		public Criteria andUserTypeLessThanOrEqualTo(Integer value) {
			addCriterion("user_type <=", value, "userType");
			return (Criteria) this;
		}

		public Criteria andUserTypeIn(List<Integer> values) {
			addCriterion("user_type in", values, "userType");
			return (Criteria) this;
		}

		public Criteria andUserTypeNotIn(List<Integer> values) {
			addCriterion("user_type not in", values, "userType");
			return (Criteria) this;
		}

		public Criteria andUserTypeBetween(Integer value1, Integer value2) {
			addCriterion("user_type between", value1, value2, "userType");
			return (Criteria) this;
		}

		public Criteria andUserTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("user_type not between", value1, value2, "userType");
			return (Criteria) this;
		}

		public Criteria andUserIdAllIsNull() {
			addCriterion("user_id_all is null");
			return (Criteria) this;
		}

		public Criteria andUserIdAllIsNotNull() {
			addCriterion("user_id_all is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdAllEqualTo(String value) {
			addCriterion("user_id_all =", value, "userIdAll");
			return (Criteria) this;
		}

		public Criteria andUserIdAllNotEqualTo(String value) {
			addCriterion("user_id_all <>", value, "userIdAll");
			return (Criteria) this;
		}

		public Criteria andUserIdAllGreaterThan(String value) {
			addCriterion("user_id_all >", value, "userIdAll");
			return (Criteria) this;
		}

		public Criteria andUserIdAllGreaterThanOrEqualTo(String value) {
			addCriterion("user_id_all >=", value, "userIdAll");
			return (Criteria) this;
		}

		public Criteria andUserIdAllLessThan(String value) {
			addCriterion("user_id_all <", value, "userIdAll");
			return (Criteria) this;
		}

		public Criteria andUserIdAllLessThanOrEqualTo(String value) {
			addCriterion("user_id_all <=", value, "userIdAll");
			return (Criteria) this;
		}

		public Criteria andUserIdAllLike(String value) {
			addCriterion("user_id_all like", value, "userIdAll");
			return (Criteria) this;
		}

		public Criteria andUserIdAllNotLike(String value) {
			addCriterion("user_id_all not like", value, "userIdAll");
			return (Criteria) this;
		}

		public Criteria andUserIdAllIn(List<String> values) {
			addCriterion("user_id_all in", values, "userIdAll");
			return (Criteria) this;
		}

		public Criteria andUserIdAllNotIn(List<String> values) {
			addCriterion("user_id_all not in", values, "userIdAll");
			return (Criteria) this;
		}

		public Criteria andUserIdAllBetween(String value1, String value2) {
			addCriterion("user_id_all between", value1, value2, "userIdAll");
			return (Criteria) this;
		}

		public Criteria andUserIdAllNotBetween(String value1, String value2) {
			addCriterion("user_id_all not between", value1, value2, "userIdAll");
			return (Criteria) this;
		}

		public Criteria andItemAllIsNull() {
			addCriterion("item_all is null");
			return (Criteria) this;
		}

		public Criteria andItemAllIsNotNull() {
			addCriterion("item_all is not null");
			return (Criteria) this;
		}

		public Criteria andItemAllEqualTo(String value) {
			addCriterion("item_all =", value, "itemAll");
			return (Criteria) this;
		}

		public Criteria andItemAllNotEqualTo(String value) {
			addCriterion("item_all <>", value, "itemAll");
			return (Criteria) this;
		}

		public Criteria andItemAllGreaterThan(String value) {
			addCriterion("item_all >", value, "itemAll");
			return (Criteria) this;
		}

		public Criteria andItemAllGreaterThanOrEqualTo(String value) {
			addCriterion("item_all >=", value, "itemAll");
			return (Criteria) this;
		}

		public Criteria andItemAllLessThan(String value) {
			addCriterion("item_all <", value, "itemAll");
			return (Criteria) this;
		}

		public Criteria andItemAllLessThanOrEqualTo(String value) {
			addCriterion("item_all <=", value, "itemAll");
			return (Criteria) this;
		}

		public Criteria andItemAllLike(String value) {
			addCriterion("item_all like", value, "itemAll");
			return (Criteria) this;
		}

		public Criteria andItemAllNotLike(String value) {
			addCriterion("item_all not like", value, "itemAll");
			return (Criteria) this;
		}

		public Criteria andItemAllIn(List<String> values) {
			addCriterion("item_all in", values, "itemAll");
			return (Criteria) this;
		}

		public Criteria andItemAllNotIn(List<String> values) {
			addCriterion("item_all not in", values, "itemAll");
			return (Criteria) this;
		}

		public Criteria andItemAllBetween(String value1, String value2) {
			addCriterion("item_all between", value1, value2, "itemAll");
			return (Criteria) this;
		}

		public Criteria andItemAllNotBetween(String value1, String value2) {
			addCriterion("item_all not between", value1, value2, "itemAll");
			return (Criteria) this;
		}

		public Criteria andStarTimeIsNull() {
			addCriterion("star_time is null");
			return (Criteria) this;
		}

		public Criteria andStarTimeIsNotNull() {
			addCriterion("star_time is not null");
			return (Criteria) this;
		}

		public Criteria andStarTimeEqualTo(Date value) {
			addCriterion("star_time =", value, "starTime");
			return (Criteria) this;
		}

		public Criteria andStarTimeNotEqualTo(Date value) {
			addCriterion("star_time <>", value, "starTime");
			return (Criteria) this;
		}

		public Criteria andStarTimeGreaterThan(Date value) {
			addCriterion("star_time >", value, "starTime");
			return (Criteria) this;
		}

		public Criteria andStarTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("star_time >=", value, "starTime");
			return (Criteria) this;
		}

		public Criteria andStarTimeLessThan(Date value) {
			addCriterion("star_time <", value, "starTime");
			return (Criteria) this;
		}

		public Criteria andStarTimeLessThanOrEqualTo(Date value) {
			addCriterion("star_time <=", value, "starTime");
			return (Criteria) this;
		}

		public Criteria andStarTimeIn(List<Date> values) {
			addCriterion("star_time in", values, "starTime");
			return (Criteria) this;
		}

		public Criteria andStarTimeNotIn(List<Date> values) {
			addCriterion("star_time not in", values, "starTime");
			return (Criteria) this;
		}

		public Criteria andStarTimeBetween(Date value1, Date value2) {
			addCriterion("star_time between", value1, value2, "starTime");
			return (Criteria) this;
		}

		public Criteria andStarTimeNotBetween(Date value1, Date value2) {
			addCriterion("star_time not between", value1, value2, "starTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeIsNull() {
			addCriterion("end_time is null");
			return (Criteria) this;
		}

		public Criteria andEndTimeIsNotNull() {
			addCriterion("end_time is not null");
			return (Criteria) this;
		}

		public Criteria andEndTimeEqualTo(Date value) {
			addCriterion("end_time =", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotEqualTo(Date value) {
			addCriterion("end_time <>", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeGreaterThan(Date value) {
			addCriterion("end_time >", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("end_time >=", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeLessThan(Date value) {
			addCriterion("end_time <", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeLessThanOrEqualTo(Date value) {
			addCriterion("end_time <=", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeIn(List<Date> values) {
			addCriterion("end_time in", values, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotIn(List<Date> values) {
			addCriterion("end_time not in", values, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeBetween(Date value1, Date value2) {
			addCriterion("end_time between", value1, value2, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotBetween(Date value1, Date value2) {
			addCriterion("end_time not between", value1, value2, "endTime");
			return (Criteria) this;
		}

		public Criteria andCreateAdminIdIsNull() {
			addCriterion("create_admin_id is null");
			return (Criteria) this;
		}

		public Criteria andCreateAdminIdIsNotNull() {
			addCriterion("create_admin_id is not null");
			return (Criteria) this;
		}

		public Criteria andCreateAdminIdEqualTo(Integer value) {
			addCriterion("create_admin_id =", value, "createAdminId");
			return (Criteria) this;
		}

		public Criteria andCreateAdminIdNotEqualTo(Integer value) {
			addCriterion("create_admin_id <>", value, "createAdminId");
			return (Criteria) this;
		}

		public Criteria andCreateAdminIdGreaterThan(Integer value) {
			addCriterion("create_admin_id >", value, "createAdminId");
			return (Criteria) this;
		}

		public Criteria andCreateAdminIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("create_admin_id >=", value, "createAdminId");
			return (Criteria) this;
		}

		public Criteria andCreateAdminIdLessThan(Integer value) {
			addCriterion("create_admin_id <", value, "createAdminId");
			return (Criteria) this;
		}

		public Criteria andCreateAdminIdLessThanOrEqualTo(Integer value) {
			addCriterion("create_admin_id <=", value, "createAdminId");
			return (Criteria) this;
		}

		public Criteria andCreateAdminIdIn(List<Integer> values) {
			addCriterion("create_admin_id in", values, "createAdminId");
			return (Criteria) this;
		}

		public Criteria andCreateAdminIdNotIn(List<Integer> values) {
			addCriterion("create_admin_id not in", values, "createAdminId");
			return (Criteria) this;
		}

		public Criteria andCreateAdminIdBetween(Integer value1, Integer value2) {
			addCriterion("create_admin_id between", value1, value2, "createAdminId");
			return (Criteria) this;
		}

		public Criteria andCreateAdminIdNotBetween(Integer value1, Integer value2) {
			addCriterion("create_admin_id not between", value1, value2, "createAdminId");
			return (Criteria) this;
		}

		public Criteria andCreateAdminNameIsNull() {
			addCriterion("create_admin_name is null");
			return (Criteria) this;
		}

		public Criteria andCreateAdminNameIsNotNull() {
			addCriterion("create_admin_name is not null");
			return (Criteria) this;
		}

		public Criteria andCreateAdminNameEqualTo(String value) {
			addCriterion("create_admin_name =", value, "createAdminName");
			return (Criteria) this;
		}

		public Criteria andCreateAdminNameNotEqualTo(String value) {
			addCriterion("create_admin_name <>", value, "createAdminName");
			return (Criteria) this;
		}

		public Criteria andCreateAdminNameGreaterThan(String value) {
			addCriterion("create_admin_name >", value, "createAdminName");
			return (Criteria) this;
		}

		public Criteria andCreateAdminNameGreaterThanOrEqualTo(String value) {
			addCriterion("create_admin_name >=", value, "createAdminName");
			return (Criteria) this;
		}

		public Criteria andCreateAdminNameLessThan(String value) {
			addCriterion("create_admin_name <", value, "createAdminName");
			return (Criteria) this;
		}

		public Criteria andCreateAdminNameLessThanOrEqualTo(String value) {
			addCriterion("create_admin_name <=", value, "createAdminName");
			return (Criteria) this;
		}

		public Criteria andCreateAdminNameLike(String value) {
			addCriterion("create_admin_name like", value, "createAdminName");
			return (Criteria) this;
		}

		public Criteria andCreateAdminNameNotLike(String value) {
			addCriterion("create_admin_name not like", value, "createAdminName");
			return (Criteria) this;
		}

		public Criteria andCreateAdminNameIn(List<String> values) {
			addCriterion("create_admin_name in", values, "createAdminName");
			return (Criteria) this;
		}

		public Criteria andCreateAdminNameNotIn(List<String> values) {
			addCriterion("create_admin_name not in", values, "createAdminName");
			return (Criteria) this;
		}

		public Criteria andCreateAdminNameBetween(String value1, String value2) {
			addCriterion("create_admin_name between", value1, value2, "createAdminName");
			return (Criteria) this;
		}

		public Criteria andCreateAdminNameNotBetween(String value1, String value2) {
			addCriterion("create_admin_name not between", value1, value2, "createAdminName");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table game_email
	 * @mbggenerated  Sun Jul 01 03:05:22 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table game_email
     *
     * @mbggenerated do_not_delete_during_merge Sun Jul 01 02:55:23 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}