package cn.springmvc.model.game;

public class GameCodeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_code_key.code
     *
     * @mbggenerated Tue Jul 24 18:44:36 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_code_key.state
     *
     * @mbggenerated Tue Jul 24 18:44:36 CST 2018
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_code_key.group_id
     *
     * @mbggenerated Tue Jul 24 18:44:36 CST 2018
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_code_key.start_time
     *
     * @mbggenerated Tue Jul 24 18:44:36 CST 2018
     */
    private Long startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_code_key.end_time
     *
     * @mbggenerated Tue Jul 24 18:44:36 CST 2018
     */
    private Long endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_code_key.item
     *
     * @mbggenerated Tue Jul 24 18:44:36 CST 2018
     */
    private String item;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_code_key.code
     *
     * @return the value of game_code_key.code
     *
     * @mbggenerated Tue Jul 24 18:44:36 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_code_key.code
     *
     * @param code the value for game_code_key.code
     *
     * @mbggenerated Tue Jul 24 18:44:36 CST 2018
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_code_key.state
     *
     * @return the value of game_code_key.state
     *
     * @mbggenerated Tue Jul 24 18:44:36 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_code_key.state
     *
     * @param state the value for game_code_key.state
     *
     * @mbggenerated Tue Jul 24 18:44:36 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_code_key.group_id
     *
     * @return the value of game_code_key.group_id
     *
     * @mbggenerated Tue Jul 24 18:44:36 CST 2018
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_code_key.group_id
     *
     * @param groupId the value for game_code_key.group_id
     *
     * @mbggenerated Tue Jul 24 18:44:36 CST 2018
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_code_key.start_time
     *
     * @return the value of game_code_key.start_time
     *
     * @mbggenerated Tue Jul 24 18:44:36 CST 2018
     */
    public Long getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_code_key.start_time
     *
     * @param startTime the value for game_code_key.start_time
     *
     * @mbggenerated Tue Jul 24 18:44:36 CST 2018
     */
    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_code_key.end_time
     *
     * @return the value of game_code_key.end_time
     *
     * @mbggenerated Tue Jul 24 18:44:36 CST 2018
     */
    public Long getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_code_key.end_time
     *
     * @param endTime the value for game_code_key.end_time
     *
     * @mbggenerated Tue Jul 24 18:44:36 CST 2018
     */
    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_code_key.item
     *
     * @return the value of game_code_key.item
     *
     * @mbggenerated Tue Jul 24 18:44:36 CST 2018
     */
    public String getItem() {
        return item;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_code_key.item
     *
     * @param item the value for game_code_key.item
     *
     * @mbggenerated Tue Jul 24 18:44:36 CST 2018
     */
    public void setItem(String item) {
        this.item = item;
    }
}