package com.rt.db.domain;

public class PlayerBeanWithBLOBs extends PlayerBean {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player.bag
	 * @mbggenerated  Wed Apr 04 11:00:16 CST 2018
	 */
	private String bag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player.skill
	 * @mbggenerated  Wed Apr 04 11:00:16 CST 2018
	 */
	private String skill;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player.equipment_column
	 * @mbggenerated  Wed Apr 04 11:00:16 CST 2018
	 */
	private String equipmentColumn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player.store_info
	 * @mbggenerated  Wed Apr 04 11:00:16 CST 2018
	 */
	private String storeInfo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player.artifact
	 * @mbggenerated  Wed Apr 04 11:00:16 CST 2018
	 */
	private String artifact;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player.arena
	 * @mbggenerated  Wed Apr 04 11:00:16 CST 2018
	 */
	private String arena;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.bag
	 * @return  the value of player.bag
	 * @mbggenerated  Wed Apr 04 11:00:16 CST 2018
	 */
	public String getBag() {
		return bag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.bag
	 * @param bag  the value for player.bag
	 * @mbggenerated  Wed Apr 04 11:00:16 CST 2018
	 */
	public void setBag(String bag) {
		this.bag = bag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.skill
	 * @return  the value of player.skill
	 * @mbggenerated  Wed Apr 04 11:00:16 CST 2018
	 */
	public String getSkill() {
		return skill;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.skill
	 * @param skill  the value for player.skill
	 * @mbggenerated  Wed Apr 04 11:00:16 CST 2018
	 */
	public void setSkill(String skill) {
		this.skill = skill;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.equipment_column
	 * @return  the value of player.equipment_column
	 * @mbggenerated  Wed Apr 04 11:00:16 CST 2018
	 */
	public String getEquipmentColumn() {
		return equipmentColumn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.equipment_column
	 * @param equipmentColumn  the value for player.equipment_column
	 * @mbggenerated  Wed Apr 04 11:00:16 CST 2018
	 */
	public void setEquipmentColumn(String equipmentColumn) {
		this.equipmentColumn = equipmentColumn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.store_info
	 * @return  the value of player.store_info
	 * @mbggenerated  Wed Apr 04 11:00:16 CST 2018
	 */
	public String getStoreInfo() {
		return storeInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.store_info
	 * @param storeInfo  the value for player.store_info
	 * @mbggenerated  Wed Apr 04 11:00:16 CST 2018
	 */
	public void setStoreInfo(String storeInfo) {
		this.storeInfo = storeInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.artifact
	 * @return  the value of player.artifact
	 * @mbggenerated  Wed Apr 04 11:00:16 CST 2018
	 */
	public String getArtifact() {
		return artifact;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.artifact
	 * @param artifact  the value for player.artifact
	 * @mbggenerated  Wed Apr 04 11:00:16 CST 2018
	 */
	public void setArtifact(String artifact) {
		this.artifact = artifact;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.arena
	 * @return  the value of player.arena
	 * @mbggenerated  Wed Apr 04 11:00:16 CST 2018
	 */
	public String getArena() {
		return arena;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.arena
	 * @param arena  the value for player.arena
	 * @mbggenerated  Wed Apr 04 11:00:16 CST 2018
	 */
	public void setArena(String arena) {
		this.arena = arena;
	}
}