package com.rt.db.mapper;

import com.rt.db.domain.RechagreOrder;
import com.rt.db.domain.RechagreOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RechagreOrderMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rechagre_order
	 * @mbggenerated  Tue Jul 24 15:16:40 CST 2018
	 */
	int countByExample(RechagreOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rechagre_order
	 * @mbggenerated  Tue Jul 24 15:16:40 CST 2018
	 */
	int deleteByExample(RechagreOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rechagre_order
	 * @mbggenerated  Tue Jul 24 15:16:40 CST 2018
	 */
	int deleteByPrimaryKey(String orderId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rechagre_order
	 * @mbggenerated  Tue Jul 24 15:16:40 CST 2018
	 */
	int insert(RechagreOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rechagre_order
	 * @mbggenerated  Tue Jul 24 15:16:40 CST 2018
	 */
	int insertSelective(RechagreOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rechagre_order
	 * @mbggenerated  Tue Jul 24 15:16:40 CST 2018
	 */
	List<RechagreOrder> selectByExample(RechagreOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rechagre_order
	 * @mbggenerated  Tue Jul 24 15:16:40 CST 2018
	 */
	RechagreOrder selectByPrimaryKey(String orderId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rechagre_order
	 * @mbggenerated  Tue Jul 24 15:16:40 CST 2018
	 */
	int updateByExampleSelective(@Param("record") RechagreOrder record, @Param("example") RechagreOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rechagre_order
	 * @mbggenerated  Tue Jul 24 15:16:40 CST 2018
	 */
	int updateByExample(@Param("record") RechagreOrder record, @Param("example") RechagreOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rechagre_order
	 * @mbggenerated  Tue Jul 24 15:16:40 CST 2018
	 */
	int updateByPrimaryKeySelective(RechagreOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rechagre_order
	 * @mbggenerated  Tue Jul 24 15:16:40 CST 2018
	 */
	int updateByPrimaryKey(RechagreOrder record);
}