package com.rt.db.domain;

public class PlayerBean {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player.player_id
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	private Long playerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player.user_id
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player.server_id
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	private Integer serverId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player.head_id
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	private Integer headId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player.job_id
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	private Integer jobId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player.player_name
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	private String playerName;
	
	private Integer sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player.gold
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	private Integer gold;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player.diamond
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	private Integer diamond;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player.fight_power
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	private Integer fightPower;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player.strengthen_artifact_stone
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	private Integer strengthenArtifactStone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player.upgrade_skills_jade
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	private Integer upgradeSkillsJade;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player.reinforced_equipment_stone
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	private Integer reinforcedEquipmentStone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player.exp
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	private Integer exp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player.level
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	private Integer level;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player.vip_level
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	private Integer vipLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player.points_id
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	private Integer pointsId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player.max_points_id
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	private Integer maxPointsId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player.rebirth_num
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	private Integer rebirthNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player.sports_money
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	private Integer sportsMoney;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player.last_login_time
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	private Long lastLoginTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player.guide_step
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	private Integer guideStep;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player.vip_exp
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	private Integer vipExp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player.history_max_pointsId
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	private Integer historyMaxPointsid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player.history_max_level
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	private Integer historyMaxLevel;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.player_id
	 * @return  the value of player.player_id
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public Long getPlayerId() {
		return playerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.player_id
	 * @param playerId  the value for player.player_id
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public void setPlayerId(Long playerId) {
		this.playerId = playerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.user_id
	 * @return  the value of player.user_id
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.user_id
	 * @param userId  the value for player.user_id
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.server_id
	 * @return  the value of player.server_id
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public Integer getServerId() {
		return serverId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.server_id
	 * @param serverId  the value for player.server_id
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public void setServerId(Integer serverId) {
		this.serverId = serverId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.head_id
	 * @return  the value of player.head_id
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public Integer getHeadId() {
		return headId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.head_id
	 * @param headId  the value for player.head_id
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public void setHeadId(Integer headId) {
		this.headId = headId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.job_id
	 * @return  the value of player.job_id
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public Integer getJobId() {
		return jobId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.job_id
	 * @param jobId  the value for player.job_id
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public void setJobId(Integer jobId) {
		this.jobId = jobId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.player_name
	 * @return  the value of player.player_name
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public String getPlayerName() {
		return playerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.player_name
	 * @param playerName  the value for player.player_name
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public void setPlayerName(String playerName) {
		this.playerName = playerName;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.player_name
	 * @return  the value of player.player_name
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public Integer getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.player_name
	 * @param playerName  the value for player.player_name
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public void setSex(Integer sex) {
		this.sex = sex;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.gold
	 * @return  the value of player.gold
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public Integer getGold() {
		return gold;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.gold
	 * @param gold  the value for player.gold
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public void setGold(Integer gold) {
		this.gold = gold;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.diamond
	 * @return  the value of player.diamond
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public Integer getDiamond() {
		return diamond;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.diamond
	 * @param diamond  the value for player.diamond
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public void setDiamond(Integer diamond) {
		this.diamond = diamond;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.fight_power
	 * @return  the value of player.fight_power
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public Integer getFightPower() {
		return fightPower;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.fight_power
	 * @param fightPower  the value for player.fight_power
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public void setFightPower(Integer fightPower) {
		this.fightPower = fightPower;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.strengthen_artifact_stone
	 * @return  the value of player.strengthen_artifact_stone
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public Integer getStrengthenArtifactStone() {
		return strengthenArtifactStone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.strengthen_artifact_stone
	 * @param strengthenArtifactStone  the value for player.strengthen_artifact_stone
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public void setStrengthenArtifactStone(Integer strengthenArtifactStone) {
		this.strengthenArtifactStone = strengthenArtifactStone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.upgrade_skills_jade
	 * @return  the value of player.upgrade_skills_jade
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public Integer getUpgradeSkillsJade() {
		return upgradeSkillsJade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.upgrade_skills_jade
	 * @param upgradeSkillsJade  the value for player.upgrade_skills_jade
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public void setUpgradeSkillsJade(Integer upgradeSkillsJade) {
		this.upgradeSkillsJade = upgradeSkillsJade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.reinforced_equipment_stone
	 * @return  the value of player.reinforced_equipment_stone
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public Integer getReinforcedEquipmentStone() {
		return reinforcedEquipmentStone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.reinforced_equipment_stone
	 * @param reinforcedEquipmentStone  the value for player.reinforced_equipment_stone
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public void setReinforcedEquipmentStone(Integer reinforcedEquipmentStone) {
		this.reinforcedEquipmentStone = reinforcedEquipmentStone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.exp
	 * @return  the value of player.exp
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public Integer getExp() {
		return exp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.exp
	 * @param exp  the value for player.exp
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public void setExp(Integer exp) {
		this.exp = exp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.level
	 * @return  the value of player.level
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public Integer getLevel() {
		return level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.level
	 * @param level  the value for player.level
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public void setLevel(Integer level) {
		this.level = level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.vip_level
	 * @return  the value of player.vip_level
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public Integer getVipLevel() {
		return vipLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.vip_level
	 * @param vipLevel  the value for player.vip_level
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public void setVipLevel(Integer vipLevel) {
		this.vipLevel = vipLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.points_id
	 * @return  the value of player.points_id
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public Integer getPointsId() {
		return pointsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.points_id
	 * @param pointsId  the value for player.points_id
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public void setPointsId(Integer pointsId) {
		this.pointsId = pointsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.max_points_id
	 * @return  the value of player.max_points_id
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public Integer getMaxPointsId() {
		return maxPointsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.max_points_id
	 * @param maxPointsId  the value for player.max_points_id
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public void setMaxPointsId(Integer maxPointsId) {
		this.maxPointsId = maxPointsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.rebirth_num
	 * @return  the value of player.rebirth_num
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public Integer getRebirthNum() {
		return rebirthNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.rebirth_num
	 * @param rebirthNum  the value for player.rebirth_num
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public void setRebirthNum(Integer rebirthNum) {
		this.rebirthNum = rebirthNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.sports_money
	 * @return  the value of player.sports_money
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public Integer getSportsMoney() {
		return sportsMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.sports_money
	 * @param sportsMoney  the value for player.sports_money
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public void setSportsMoney(Integer sportsMoney) {
		this.sportsMoney = sportsMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.last_login_time
	 * @return  the value of player.last_login_time
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public Long getLastLoginTime() {
		return lastLoginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.last_login_time
	 * @param lastLoginTime  the value for player.last_login_time
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public void setLastLoginTime(Long lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.guide_step
	 * @return  the value of player.guide_step
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public Integer getGuideStep() {
		return guideStep;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.guide_step
	 * @param guideStep  the value for player.guide_step
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public void setGuideStep(Integer guideStep) {
		this.guideStep = guideStep;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.vip_exp
	 * @return  the value of player.vip_exp
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public Integer getVipExp() {
		return vipExp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.vip_exp
	 * @param vipExp  the value for player.vip_exp
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public void setVipExp(Integer vipExp) {
		this.vipExp = vipExp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.history_max_pointsId
	 * @return  the value of player.history_max_pointsId
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public Integer getHistoryMaxPointsid() {
		return historyMaxPointsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.history_max_pointsId
	 * @param historyMaxPointsid  the value for player.history_max_pointsId
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public void setHistoryMaxPointsid(Integer historyMaxPointsid) {
		this.historyMaxPointsid = historyMaxPointsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.history_max_level
	 * @return  the value of player.history_max_level
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public Integer getHistoryMaxLevel() {
		return historyMaxLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.history_max_level
	 * @param historyMaxLevel  the value for player.history_max_level
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public void setHistoryMaxLevel(Integer historyMaxLevel) {
		this.historyMaxLevel = historyMaxLevel;
	}
}