package com.rt.db.domain;

public class PlayerBeanWithBLOBs extends PlayerBean {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player.bag
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	private String bag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player.skill
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	private String skill;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player.equipment_column
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	private String equipmentColumn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player.store_info
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	private String storeInfo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player.artifact
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	private String artifact;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player.arena
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	private String arena;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player.player_task
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	private String playerTask;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player.part_info
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	private String partInfo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player.activity_info
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	private String activityInfo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player.player_email
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	private String playerEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player.draw_card_info
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	private String drawCardInfo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player.vip_receive_lev
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	private String vipReceiveLev;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player.month_card_info
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	private String monthCardInfo;
	
	private String playerAttrInfo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column player.use_giftcode_list
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	private String useGiftcodeList;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.bag
	 * @return  the value of player.bag
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public String getBag() {
		return bag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.bag
	 * @param bag  the value for player.bag
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public void setBag(String bag) {
		this.bag = bag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.skill
	 * @return  the value of player.skill
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public String getSkill() {
		return skill;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.skill
	 * @param skill  the value for player.skill
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public void setSkill(String skill) {
		this.skill = skill;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.equipment_column
	 * @return  the value of player.equipment_column
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public String getEquipmentColumn() {
		return equipmentColumn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.equipment_column
	 * @param equipmentColumn  the value for player.equipment_column
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public void setEquipmentColumn(String equipmentColumn) {
		this.equipmentColumn = equipmentColumn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.store_info
	 * @return  the value of player.store_info
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public String getStoreInfo() {
		return storeInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.store_info
	 * @param storeInfo  the value for player.store_info
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public void setStoreInfo(String storeInfo) {
		this.storeInfo = storeInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.artifact
	 * @return  the value of player.artifact
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public String getArtifact() {
		return artifact;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.artifact
	 * @param artifact  the value for player.artifact
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public void setArtifact(String artifact) {
		this.artifact = artifact;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.arena
	 * @return  the value of player.arena
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public String getArena() {
		return arena;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.arena
	 * @param arena  the value for player.arena
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public void setArena(String arena) {
		this.arena = arena;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.player_task
	 * @return  the value of player.player_task
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public String getPlayerTask() {
		return playerTask;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.player_task
	 * @param playerTask  the value for player.player_task
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public void setPlayerTask(String playerTask) {
		this.playerTask = playerTask;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.part_info
	 * @return  the value of player.part_info
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public String getPartInfo() {
		return partInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.part_info
	 * @param partInfo  the value for player.part_info
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public void setPartInfo(String partInfo) {
		this.partInfo = partInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.activity_info
	 * @return  the value of player.activity_info
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public String getActivityInfo() {
		return activityInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.activity_info
	 * @param activityInfo  the value for player.activity_info
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public void setActivityInfo(String activityInfo) {
		this.activityInfo = activityInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.player_email
	 * @return  the value of player.player_email
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public String getPlayerEmail() {
		return playerEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.player_email
	 * @param playerEmail  the value for player.player_email
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public void setPlayerEmail(String playerEmail) {
		this.playerEmail = playerEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.draw_card_info
	 * @return  the value of player.draw_card_info
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public String getDrawCardInfo() {
		return drawCardInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.draw_card_info
	 * @param drawCardInfo  the value for player.draw_card_info
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public void setDrawCardInfo(String drawCardInfo) {
		this.drawCardInfo = drawCardInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.vip_receive_lev
	 * @return  the value of player.vip_receive_lev
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public String getVipReceiveLev() {
		return vipReceiveLev;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.vip_receive_lev
	 * @param vipReceiveLev  the value for player.vip_receive_lev
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public void setVipReceiveLev(String vipReceiveLev) {
		this.vipReceiveLev = vipReceiveLev;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.month_card_info
	 * @return  the value of player.month_card_info
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public String getMonthCardInfo() {
		return monthCardInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.month_card_info
	 * @param monthCardInfo  the value for player.month_card_info
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public void setMonthCardInfo(String monthCardInfo) {
		this.monthCardInfo = monthCardInfo;
	}

	
	public String getPlayerAttrInfo() {
		return playerAttrInfo;
	}
	public void setPlayerAttrInfo(String info) {
		this.playerAttrInfo = info;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column player.use_giftcode_list
	 * @return  the value of player.use_giftcode_list
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public String getUseGiftcodeList() {
		return useGiftcodeList;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column player.use_giftcode_list
	 * @param useGiftcodeList  the value for player.use_giftcode_list
	 * @mbggenerated  Thu Aug 30 11:19:14 CST 2018
	 */
	public void setUseGiftcodeList(String useGiftcodeList) {
		this.useGiftcodeList = useGiftcodeList;
	}
}