package cn.springmvc.model.usermodel;

import java.util.Date;

import cn.springmvc.model.sys.LogExplain;

public class Admin {
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.id
	 * @mbggenerated  Wed Jun 27 15:31:28 CST 2018
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.login_name
	 * @mbggenerated  Wed Jun 27 15:31:28 CST 2018
	 */
	private String loginName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.yian_password
	 * @mbggenerated  Wed Jun 27 15:31:28 CST 2018
	 */
	private String yianPassword;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.name
	 * @mbggenerated  Wed Jun 27 15:31:28 CST 2018
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.mobile
	 * @mbggenerated  Wed Jun 27 15:31:28 CST 2018
	 */
	private String mobile;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.department
	 * @mbggenerated  Wed Jun 27 15:31:28 CST 2018
	 */
	private String department;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.state
	 * @mbggenerated  Wed Jun 27 15:31:28 CST 2018
	 */
	private Integer state;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.create_time
	 * @mbggenerated  Wed Jun 27 15:31:28 CST 2018
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.last_login_time
	 * @mbggenerated  Wed Jun 27 15:31:28 CST 2018
	 */
	private Date lastLoginTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.last_login_ip
	 * @mbggenerated  Wed Jun 27 15:31:28 CST 2018
	 */
	private String lastLoginIp;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.email
	 * @mbggenerated  Wed Jun 27 15:31:28 CST 2018
	 */
	private String email;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.channel_id
	 * @mbggenerated  Wed Jun 27 15:31:28 CST 2018
	 */
	private Integer channelId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.id
	 * @return  the value of admin.id
	 * @mbggenerated  Wed Jun 27 15:31:28 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.id
	 * @param id  the value for admin.id
	 * @mbggenerated  Wed Jun 27 15:31:28 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.login_name
	 * @return  the value of admin.login_name
	 * @mbggenerated  Wed Jun 27 15:31:28 CST 2018
	 */
	public String getLoginName() {
		return loginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.login_name
	 * @param loginName  the value for admin.login_name
	 * @mbggenerated  Wed Jun 27 15:31:28 CST 2018
	 */
	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.yian_password
	 * @return  the value of admin.yian_password
	 * @mbggenerated  Wed Jun 27 15:31:28 CST 2018
	 */
	public String getYianPassword() {
		return yianPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.yian_password
	 * @param yianPassword  the value for admin.yian_password
	 * @mbggenerated  Wed Jun 27 15:31:28 CST 2018
	 */
	public void setYianPassword(String yianPassword) {
		this.yianPassword = yianPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.name
	 * @return  the value of admin.name
	 * @mbggenerated  Wed Jun 27 15:31:28 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.name
	 * @param name  the value for admin.name
	 * @mbggenerated  Wed Jun 27 15:31:28 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.mobile
	 * @return  the value of admin.mobile
	 * @mbggenerated  Wed Jun 27 15:31:28 CST 2018
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.mobile
	 * @param mobile  the value for admin.mobile
	 * @mbggenerated  Wed Jun 27 15:31:28 CST 2018
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.department
	 * @return  the value of admin.department
	 * @mbggenerated  Wed Jun 27 15:31:28 CST 2018
	 */
	public String getDepartment() {
		return department;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.department
	 * @param department  the value for admin.department
	 * @mbggenerated  Wed Jun 27 15:31:28 CST 2018
	 */
	public void setDepartment(String department) {
		this.department = department;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.state
	 * @return  the value of admin.state
	 * @mbggenerated  Wed Jun 27 15:31:28 CST 2018
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.state
	 * @param state  the value for admin.state
	 * @mbggenerated  Wed Jun 27 15:31:28 CST 2018
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.create_time
	 * @return  the value of admin.create_time
	 * @mbggenerated  Wed Jun 27 15:31:28 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.create_time
	 * @param createTime  the value for admin.create_time
	 * @mbggenerated  Wed Jun 27 15:31:28 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.last_login_time
	 * @return  the value of admin.last_login_time
	 * @mbggenerated  Wed Jun 27 15:31:28 CST 2018
	 */
	public Date getLastLoginTime() {
		return lastLoginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.last_login_time
	 * @param lastLoginTime  the value for admin.last_login_time
	 * @mbggenerated  Wed Jun 27 15:31:28 CST 2018
	 */
	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.last_login_ip
	 * @return  the value of admin.last_login_ip
	 * @mbggenerated  Wed Jun 27 15:31:28 CST 2018
	 */
	public String getLastLoginIp() {
		return lastLoginIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.last_login_ip
	 * @param lastLoginIp  the value for admin.last_login_ip
	 * @mbggenerated  Wed Jun 27 15:31:28 CST 2018
	 */
	public void setLastLoginIp(String lastLoginIp) {
		this.lastLoginIp = lastLoginIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.email
	 * @return  the value of admin.email
	 * @mbggenerated  Wed Jun 27 15:31:28 CST 2018
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.email
	 * @param email  the value for admin.email
	 * @mbggenerated  Wed Jun 27 15:31:28 CST 2018
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.channel_id
	 * @return  the value of admin.channel_id
	 * @mbggenerated  Wed Jun 27 15:31:28 CST 2018
	 */
	public Integer getChannelId() {
		return channelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.channel_id
	 * @param channelId  the value for admin.channel_id
	 * @mbggenerated  Wed Jun 27 15:31:28 CST 2018
	 */
	public void setChannelId(Integer channelId) {
		this.channelId = channelId;
	}


	

	private LogExplain logExplain;

	public LogExplain getLogExplain() {
		return logExplain;
	}

	public void setLogExplain(LogExplain logExplain) {
		this.logExplain = logExplain;
	}

	private Date lastLoginTime_;

	private String lastLoginIp_;
	
	private Integer pageNo;
	
	private Integer pageSize;
	
	private int first_login;

	public int getFirst_login() {
		return first_login;
	}

	public void setFirst_login(int first_login) {
		this.first_login = first_login;
	}

	public Integer getPageNo() {
		return pageNo;
	}

	public void setPageNo(Integer pageNo) {
		this.pageNo = pageNo;
	}

	public Integer getPageSize() {
		return pageSize;
	}

	public void setPageSize(Integer pageSize) {
		this.pageSize = pageSize;
	}

	public Date getLastLoginTime_() {
		return lastLoginTime_;
	}

	public void setLastLoginTime_(Date lastLoginTime_) {
		this.lastLoginTime_ = lastLoginTime_;
	}

	public String getLastLoginIp_() {
		return lastLoginIp_;
	}

	public void setLastLoginIp_(String lastLoginIp_) {
		this.lastLoginIp_ = lastLoginIp_;
	}
}