package cn.springmvc.model.usermodel;

import java.util.Date;

public class SecurityCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_code.id
     *
     * @mbggenerated Thu Jan 05 16:40:17 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_code.email
     *
     * @mbggenerated Thu Jan 05 16:40:17 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_code.security_code
     *
     * @mbggenerated Thu Jan 05 16:40:17 CST 2017
     */
    private String securityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_code.create_time
     *
     * @mbggenerated Thu Jan 05 16:40:17 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_code.id
     *
     * @return the value of security_code.id
     *
     * @mbggenerated Thu Jan 05 16:40:17 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_code.id
     *
     * @param id the value for security_code.id
     *
     * @mbggenerated Thu Jan 05 16:40:17 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_code.email
     *
     * @return the value of security_code.email
     *
     * @mbggenerated Thu Jan 05 16:40:17 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_code.email
     *
     * @param email the value for security_code.email
     *
     * @mbggenerated Thu Jan 05 16:40:17 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_code.security_code
     *
     * @return the value of security_code.security_code
     *
     * @mbggenerated Thu Jan 05 16:40:17 CST 2017
     */
    public String getSecurityCode() {
        return securityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_code.security_code
     *
     * @param securityCode the value for security_code.security_code
     *
     * @mbggenerated Thu Jan 05 16:40:17 CST 2017
     */
    public void setSecurityCode(String securityCode) {
        this.securityCode = securityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_code.create_time
     *
     * @return the value of security_code.create_time
     *
     * @mbggenerated Thu Jan 05 16:40:17 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_code.create_time
     *
     * @param createTime the value for security_code.create_time
     *
     * @mbggenerated Thu Jan 05 16:40:17 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}