package cn.springmvc.dao.mall;

import cn.springmvc.model.mall.Mall;
import cn.springmvc.model.mall.MallExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MallMapper {
	
	 /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mall
	 * @mbggenerated  Thu May 10 19:21:03 CST 2018
	 */
	int countByExample(MallExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mall
	 * @mbggenerated  Thu May 10 19:21:03 CST 2018
	 */
	int deleteByExample(MallExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mall
	 * @mbggenerated  Thu May 10 19:21:03 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mall
	 * @mbggenerated  Thu May 10 19:21:03 CST 2018
	 */
	int insert(Mall record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mall
	 * @mbggenerated  Thu May 10 19:21:03 CST 2018
	 */
	int insertSelective(Mall record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mall
	 * @mbggenerated  Thu May 10 19:21:03 CST 2018
	 */List<Mall> selectByExample(MallExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mall
	 * @mbggenerated  Thu May 10 19:21:03 CST 2018
	 */
	Mall selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mall
	 * @mbggenerated  Thu May 10 19:21:03 CST 2018
	 */int updateByExampleSelective(@Param("record") Mall record,@Param("example") MallExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mall
	 * @mbggenerated  Thu May 10 19:21:03 CST 2018
	 */int updateByExample(@Param("record") Mall record,@Param("example") MallExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mall
	 * @mbggenerated  Thu May 10 19:21:03 CST 2018
	 */
	int updateByPrimaryKeySelective(Mall record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mall
	 * @mbggenerated  Thu May 10 19:21:03 CST 2018
	 */
	int updateByPrimaryKey(Mall record);

	public List<Mall> listLimitMall(@Param("record")Mall mall);
}