package cn.springmvc.dao.poster;

import cn.springmvc.model.poster.WxpayFlowingWater;
import cn.springmvc.model.poster.WxpayFlowingWaterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WxpayFlowingWaterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxpay_flowing_water
     *
     * @mbggenerated Wed Jun 27 01:14:41 CST 2018
     */
    int countByExample(WxpayFlowingWaterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxpay_flowing_water
     *
     * @mbggenerated Wed Jun 27 01:14:41 CST 2018
     */
    int deleteByExample(WxpayFlowingWaterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxpay_flowing_water
     *
     * @mbggenerated Wed Jun 27 01:14:41 CST 2018
     */
    int deleteByPrimaryKey(String outTradeNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxpay_flowing_water
     *
     * @mbggenerated Wed Jun 27 01:14:41 CST 2018
     */
    int insert(WxpayFlowingWater record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxpay_flowing_water
     *
     * @mbggenerated Wed Jun 27 01:14:41 CST 2018
     */
    int insertSelective(WxpayFlowingWater record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxpay_flowing_water
     *
     * @mbggenerated Wed Jun 27 01:14:41 CST 2018
     */
    List<WxpayFlowingWater> selectByExample(WxpayFlowingWaterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxpay_flowing_water
     *
     * @mbggenerated Wed Jun 27 01:14:41 CST 2018
     */
    WxpayFlowingWater selectByPrimaryKey(String outTradeNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxpay_flowing_water
     *
     * @mbggenerated Wed Jun 27 01:14:41 CST 2018
     */
    int updateByExampleSelective(@Param("record") WxpayFlowingWater record, @Param("example") WxpayFlowingWaterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxpay_flowing_water
     *
     * @mbggenerated Wed Jun 27 01:14:41 CST 2018
     */
    int updateByExample(@Param("record") WxpayFlowingWater record, @Param("example") WxpayFlowingWaterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxpay_flowing_water
     *
     * @mbggenerated Wed Jun 27 01:14:41 CST 2018
     */
    int updateByPrimaryKeySelective(WxpayFlowingWater record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxpay_flowing_water
     *
     * @mbggenerated Wed Jun 27 01:14:41 CST 2018
     */
    int updateByPrimaryKey(WxpayFlowingWater record);
}