package com.rt.db.domain;

public class ServerInfoBean {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column server_list.server_id
	 * @mbg.generated  Sat Feb 03 21:00:08 CST 2018
	 */
	private Integer serverId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column server_list.server_name
	 * @mbg.generated  Sat Feb 03 21:00:08 CST 2018
	 */
	private String serverName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column server_list.server_ip
	 * @mbg.generated  Sat Feb 03 21:00:08 CST 2018
	 */
	private String serverIp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column server_list.server_port
	 * @mbg.generated  Sat Feb 03 21:00:08 CST 2018
	 */
	private Integer serverPort;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column server_list.server_address
	 * @mbg.generated  Sat Feb 03 21:00:08 CST 2018
	 */
	private String serverAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column server_list.open_time
	 * @mbg.generated  Sat Feb 03 21:00:08 CST 2018
	 */
	private Long openTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column server_list.server_id
	 * @return  the value of server_list.server_id
	 * @mbg.generated  Sat Feb 03 21:00:08 CST 2018
	 */
	public Integer getServerId() {
		return serverId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column server_list.server_id
	 * @param serverId  the value for server_list.server_id
	 * @mbg.generated  Sat Feb 03 21:00:08 CST 2018
	 */
	public void setServerId(Integer serverId) {
		this.serverId = serverId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column server_list.server_name
	 * @return  the value of server_list.server_name
	 * @mbg.generated  Sat Feb 03 21:00:08 CST 2018
	 */
	public String getServerName() {
		return serverName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column server_list.server_name
	 * @param serverName  the value for server_list.server_name
	 * @mbg.generated  Sat Feb 03 21:00:08 CST 2018
	 */
	public void setServerName(String serverName) {
		this.serverName = serverName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column server_list.server_ip
	 * @return  the value of server_list.server_ip
	 * @mbg.generated  Sat Feb 03 21:00:08 CST 2018
	 */
	public String getServerIp() {
		return serverIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column server_list.server_ip
	 * @param serverIp  the value for server_list.server_ip
	 * @mbg.generated  Sat Feb 03 21:00:08 CST 2018
	 */
	public void setServerIp(String serverIp) {
		this.serverIp = serverIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column server_list.server_port
	 * @return  the value of server_list.server_port
	 * @mbg.generated  Sat Feb 03 21:00:08 CST 2018
	 */
	public Integer getServerPort() {
		return serverPort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column server_list.server_port
	 * @param serverPort  the value for server_list.server_port
	 * @mbg.generated  Sat Feb 03 21:00:08 CST 2018
	 */
	public void setServerPort(Integer serverPort) {
		this.serverPort = serverPort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column server_list.server_address
	 * @return  the value of server_list.server_address
	 * @mbg.generated  Sat Feb 03 21:00:08 CST 2018
	 */
	public String getServerAddress() {
		return serverAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column server_list.server_address
	 * @param serverAddress  the value for server_list.server_address
	 * @mbg.generated  Sat Feb 03 21:00:08 CST 2018
	 */
	public void setServerAddress(String serverAddress) {
		this.serverAddress = serverAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column server_list.open_time
	 * @return  the value of server_list.open_time
	 * @mbg.generated  Sat Feb 03 21:00:08 CST 2018
	 */
	public Long getOpenTime() {
		return openTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column server_list.open_time
	 * @param openTime  the value for server_list.open_time
	 * @mbg.generated  Sat Feb 03 21:00:08 CST 2018
	 */
	public void setOpenTime(Long openTime) {
		this.openTime = openTime;
	}
}