package com.rt.db.mapper;

import com.rt.db.domain.ServerInfoBean;
import com.rt.db.domain.ServerInfoBeanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ServerInfoBeanMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_list
	 * @mbg.generated  Sat Feb 03 21:00:08 CST 2018
	 */
	long countByExample(ServerInfoBeanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_list
	 * @mbg.generated  Sat Feb 03 21:00:08 CST 2018
	 */
	int deleteByExample(ServerInfoBeanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_list
	 * @mbg.generated  Sat Feb 03 21:00:08 CST 2018
	 */
	int deleteByPrimaryKey(Integer serverId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_list
	 * @mbg.generated  Sat Feb 03 21:00:08 CST 2018
	 */
	int insert(ServerInfoBean record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_list
	 * @mbg.generated  Sat Feb 03 21:00:08 CST 2018
	 */
	int insertSelective(ServerInfoBean record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_list
	 * @mbg.generated  Sat Feb 03 21:00:08 CST 2018
	 */
	List<ServerInfoBean> selectByExample(ServerInfoBeanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_list
	 * @mbg.generated  Sat Feb 03 21:00:08 CST 2018
	 */
	ServerInfoBean selectByPrimaryKey(Integer serverId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_list
	 * @mbg.generated  Sat Feb 03 21:00:08 CST 2018
	 */
	int updateByExampleSelective(@Param("record") ServerInfoBean record,
			@Param("example") ServerInfoBeanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_list
	 * @mbg.generated  Sat Feb 03 21:00:08 CST 2018
	 */
	int updateByExample(@Param("record") ServerInfoBean record, @Param("example") ServerInfoBeanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_list
	 * @mbg.generated  Sat Feb 03 21:00:08 CST 2018
	 */
	int updateByPrimaryKeySelective(ServerInfoBean record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_list
	 * @mbg.generated  Sat Feb 03 21:00:08 CST 2018
	 */
	int updateByPrimaryKey(ServerInfoBean record);
}