package com.rt.db.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.rt.db.domain.UserBean;
import com.rt.db.domain.UserBeanExample;

public interface UserBeanMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Sat Feb 03 21:58:39 CST 2018
	 */
	long countByExample(UserBeanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Sat Feb 03 21:58:39 CST 2018
	 */
	int deleteByExample(UserBeanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Sat Feb 03 21:58:39 CST 2018
	 */
	int deleteByPrimaryKey(Long userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Sat Feb 03 21:58:39 CST 2018
	 */
	int insert(UserBean record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Sat Feb 03 21:58:39 CST 2018
	 */
	int insertSelective(UserBean record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Sat Feb 03 21:58:39 CST 2018
	 */
	List<UserBean> selectByExample(UserBeanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Sat Feb 03 21:58:39 CST 2018
	 */
	UserBean selectByPrimaryKey(Long userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Sat Feb 03 21:58:39 CST 2018
	 */
	int updateByExampleSelective(@Param("record") UserBean record, @Param("example") UserBeanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Sat Feb 03 21:58:39 CST 2018
	 */
	int updateByExample(@Param("record") UserBean record, @Param("example") UserBeanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Sat Feb 03 21:58:39 CST 2018
	 */
	int updateByPrimaryKeySelective(UserBean record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Sat Feb 03 21:58:39 CST 2018
	 */
	int updateByPrimaryKey(UserBean record);
}